name: CI
on:    
  push:
    branches: 
    - master
jobs:
  "build-daemon":
    name: "Build Amule Daemon"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2   
    - name: Docker Build and Publish
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:        
        name: segator/amuled
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}        
        workdir: amule-daemon
  "build-gui":    
    name: "Build Amule GUI"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Build and Publish
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:        
        name: segator/amulegui
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}        
        workdir: amule-gui        
