name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Daemon
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:        
        name: segator/amule
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}        
        workdir: amule-daemon
        tag_names: daemon
    - name: Build GUI
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:        
        name: segator/amule
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}        
        workdir: amule-gui
        tag_names: gui
